"""create_table_artist

Revision ID: 0b5c1b27865c
Revises: 1d649d8e07e8
Create Date: 2024-08-17 22:57:24.090404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5c1b27865c'
down_revision: Union[str, None] = '1d649d8e07e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('str_username', sa.String(), nullable=False),
    sa.Column('qntd_seguidores', sa.String(), nullable=False),
    sa.Column('popularidade', sa.String(), nullable=False),
    sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
    sa.Column('audit_created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_updated_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artists')
    # ### end Alembic commands ###
